# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/snort3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/snort3/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/deb: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig_DEB.cmake
.PHONY : package/deb

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/ubuntu/snort3/build/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/snort3/build/CMakeFiles /home/ubuntu/snort3/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/snort3/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named snort

# Build rule for target.
snort: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snort
.PHONY : snort

# fast build rule for target.
snort/fast:
	$(MAKE) -f src/CMakeFiles/snort.dir/build.make src/CMakeFiles/snort.dir/build
.PHONY : snort/fast

#=============================================================================
# Target rules for targets named ips_actions

# Build rule for target.
ips_actions: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ips_actions
.PHONY : ips_actions

# fast build rule for target.
ips_actions/fast:
	$(MAKE) -f src/actions/CMakeFiles/ips_actions.dir/build.make src/actions/CMakeFiles/ips_actions.dir/build
.PHONY : ips_actions/fast

#=============================================================================
# Target rules for targets named codecs

# Build rule for target.
codecs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 codecs
.PHONY : codecs

# fast build rule for target.
codecs/fast:
	$(MAKE) -f src/codecs/CMakeFiles/codecs.dir/build.make src/codecs/CMakeFiles/codecs.dir/build
.PHONY : codecs/fast

#=============================================================================
# Target rules for targets named root_codecs

# Build rule for target.
root_codecs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 root_codecs
.PHONY : root_codecs

# fast build rule for target.
root_codecs/fast:
	$(MAKE) -f src/codecs/root/CMakeFiles/root_codecs.dir/build.make src/codecs/root/CMakeFiles/root_codecs.dir/build
.PHONY : root_codecs/fast

#=============================================================================
# Target rules for targets named link_codecs

# Build rule for target.
link_codecs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 link_codecs
.PHONY : link_codecs

# fast build rule for target.
link_codecs/fast:
	$(MAKE) -f src/codecs/link/CMakeFiles/link_codecs.dir/build.make src/codecs/link/CMakeFiles/link_codecs.dir/build
.PHONY : link_codecs/fast

#=============================================================================
# Target rules for targets named ip_codecs

# Build rule for target.
ip_codecs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ip_codecs
.PHONY : ip_codecs

# fast build rule for target.
ip_codecs/fast:
	$(MAKE) -f src/codecs/ip/CMakeFiles/ip_codecs.dir/build.make src/codecs/ip/CMakeFiles/ip_codecs.dir/build
.PHONY : ip_codecs/fast

#=============================================================================
# Target rules for targets named misc_codecs

# Build rule for target.
misc_codecs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 misc_codecs
.PHONY : misc_codecs

# fast build rule for target.
misc_codecs/fast:
	$(MAKE) -f src/codecs/misc/CMakeFiles/misc_codecs.dir/build.make src/codecs/misc/CMakeFiles/misc_codecs.dir/build
.PHONY : misc_codecs/fast

#=============================================================================
# Target rules for targets named control

# Build rule for target.
control: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 control
.PHONY : control

# fast build rule for target.
control/fast:
	$(MAKE) -f src/control/CMakeFiles/control.dir/build.make src/control/CMakeFiles/control.dir/build
.PHONY : control/fast

#=============================================================================
# Target rules for targets named detection

# Build rule for target.
detection: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 detection
.PHONY : detection

# fast build rule for target.
detection/fast:
	$(MAKE) -f src/detection/CMakeFiles/detection.dir/build.make src/detection/CMakeFiles/detection.dir/build
.PHONY : detection/fast

#=============================================================================
# Target rules for targets named events

# Build rule for target.
events: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 events
.PHONY : events

# fast build rule for target.
events/fast:
	$(MAKE) -f src/events/CMakeFiles/events.dir/build.make src/events/CMakeFiles/events.dir/build
.PHONY : events/fast

#=============================================================================
# Target rules for targets named file_api

# Build rule for target.
file_api: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_api
.PHONY : file_api

# fast build rule for target.
file_api/fast:
	$(MAKE) -f src/file_api/CMakeFiles/file_api.dir/build.make src/file_api/CMakeFiles/file_api.dir/build
.PHONY : file_api/fast

#=============================================================================
# Target rules for targets named filter

# Build rule for target.
filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 filter
.PHONY : filter

# fast build rule for target.
filter/fast:
	$(MAKE) -f src/filters/CMakeFiles/filter.dir/build.make src/filters/CMakeFiles/filter.dir/build
.PHONY : filter/fast

#=============================================================================
# Target rules for targets named flow

# Build rule for target.
flow: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flow
.PHONY : flow

# fast build rule for target.
flow/fast:
	$(MAKE) -f src/flow/CMakeFiles/flow.dir/build.make src/flow/CMakeFiles/flow.dir/build
.PHONY : flow/fast

#=============================================================================
# Target rules for targets named framework

# Build rule for target.
framework: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 framework
.PHONY : framework

# fast build rule for target.
framework/fast:
	$(MAKE) -f src/framework/CMakeFiles/framework.dir/build.make src/framework/CMakeFiles/framework.dir/build
.PHONY : framework/fast

#=============================================================================
# Target rules for targets named api_options

# Build rule for target.
api_options: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 api_options
.PHONY : api_options

# fast build rule for target.
api_options/fast:
	$(MAKE) -f src/framework/CMakeFiles/api_options.dir/build.make src/framework/CMakeFiles/api_options.dir/build
.PHONY : api_options/fast

#=============================================================================
# Target rules for targets named hash

# Build rule for target.
hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash
.PHONY : hash

# fast build rule for target.
hash/fast:
	$(MAKE) -f src/hash/CMakeFiles/hash.dir/build.make src/hash/CMakeFiles/hash.dir/build
.PHONY : hash/fast

#=============================================================================
# Target rules for targets named latency

# Build rule for target.
latency: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 latency
.PHONY : latency

# fast build rule for target.
latency/fast:
	$(MAKE) -f src/latency/CMakeFiles/latency.dir/build.make src/latency/CMakeFiles/latency.dir/build
.PHONY : latency/fast

#=============================================================================
# Target rules for targets named log

# Build rule for target.
log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log
.PHONY : log

# fast build rule for target.
log/fast:
	$(MAKE) -f src/log/CMakeFiles/log.dir/build.make src/log/CMakeFiles/log.dir/build
.PHONY : log/fast

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f src/main/CMakeFiles/main.dir/build.make src/main/CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named managers

# Build rule for target.
managers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 managers
.PHONY : managers

# fast build rule for target.
managers/fast:
	$(MAKE) -f src/managers/CMakeFiles/managers.dir/build.make src/managers/CMakeFiles/managers.dir/build
.PHONY : managers/fast

#=============================================================================
# Target rules for targets named memory

# Build rule for target.
memory: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memory
.PHONY : memory

# fast build rule for target.
memory/fast:
	$(MAKE) -f src/memory/CMakeFiles/memory.dir/build.make src/memory/CMakeFiles/memory.dir/build
.PHONY : memory/fast

#=============================================================================
# Target rules for targets named mime

# Build rule for target.
mime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mime
.PHONY : mime

# fast build rule for target.
mime/fast:
	$(MAKE) -f src/mime/CMakeFiles/mime.dir/build.make src/mime/CMakeFiles/mime.dir/build
.PHONY : mime/fast

#=============================================================================
# Target rules for targets named packet_io

# Build rule for target.
packet_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 packet_io
.PHONY : packet_io

# fast build rule for target.
packet_io/fast:
	$(MAKE) -f src/packet_io/CMakeFiles/packet_io.dir/build.make src/packet_io/CMakeFiles/packet_io.dir/build
.PHONY : packet_io/fast

#=============================================================================
# Target rules for targets named parser

# Build rule for target.
parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parser
.PHONY : parser

# fast build rule for target.
parser/fast:
	$(MAKE) -f src/parser/CMakeFiles/parser.dir/build.make src/parser/CMakeFiles/parser.dir/build
.PHONY : parser/fast

#=============================================================================
# Target rules for targets named ports

# Build rule for target.
ports: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ports
.PHONY : ports

# fast build rule for target.
ports/fast:
	$(MAKE) -f src/ports/CMakeFiles/ports.dir/build.make src/ports/CMakeFiles/ports.dir/build
.PHONY : ports/fast

#=============================================================================
# Target rules for targets named protocols

# Build rule for target.
protocols: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 protocols
.PHONY : protocols

# fast build rule for target.
protocols/fast:
	$(MAKE) -f src/protocols/CMakeFiles/protocols.dir/build.make src/protocols/CMakeFiles/protocols.dir/build
.PHONY : protocols/fast

#=============================================================================
# Target rules for targets named sfip

# Build rule for target.
sfip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfip
.PHONY : sfip

# fast build rule for target.
sfip/fast:
	$(MAKE) -f src/sfip/CMakeFiles/sfip.dir/build.make src/sfip/CMakeFiles/sfip.dir/build
.PHONY : sfip/fast

#=============================================================================
# Target rules for targets named sfrt

# Build rule for target.
sfrt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfrt
.PHONY : sfrt

# fast build rule for target.
sfrt/fast:
	$(MAKE) -f src/sfrt/CMakeFiles/sfrt.dir/build.make src/sfrt/CMakeFiles/sfrt.dir/build
.PHONY : sfrt/fast

#=============================================================================
# Target rules for targets named service_inspectors

# Build rule for target.
service_inspectors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 service_inspectors
.PHONY : service_inspectors

# fast build rule for target.
service_inspectors/fast:
	$(MAKE) -f src/service_inspectors/CMakeFiles/service_inspectors.dir/build.make src/service_inspectors/CMakeFiles/service_inspectors.dir/build
.PHONY : service_inspectors/fast

#=============================================================================
# Target rules for targets named back_orifice

# Build rule for target.
back_orifice: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 back_orifice
.PHONY : back_orifice

# fast build rule for target.
back_orifice/fast:
	$(MAKE) -f src/service_inspectors/back_orifice/CMakeFiles/back_orifice.dir/build.make src/service_inspectors/back_orifice/CMakeFiles/back_orifice.dir/build
.PHONY : back_orifice/fast

#=============================================================================
# Target rules for targets named dce_rpc

# Build rule for target.
dce_rpc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dce_rpc
.PHONY : dce_rpc

# fast build rule for target.
dce_rpc/fast:
	$(MAKE) -f src/service_inspectors/dce_rpc/CMakeFiles/dce_rpc.dir/build.make src/service_inspectors/dce_rpc/CMakeFiles/dce_rpc.dir/build
.PHONY : dce_rpc/fast

#=============================================================================
# Target rules for targets named dnp3

# Build rule for target.
dnp3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dnp3
.PHONY : dnp3

# fast build rule for target.
dnp3/fast:
	$(MAKE) -f src/service_inspectors/dnp3/CMakeFiles/dnp3.dir/build.make src/service_inspectors/dnp3/CMakeFiles/dnp3.dir/build
.PHONY : dnp3/fast

#=============================================================================
# Target rules for targets named dns

# Build rule for target.
dns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dns
.PHONY : dns

# fast build rule for target.
dns/fast:
	$(MAKE) -f src/service_inspectors/dns/CMakeFiles/dns.dir/build.make src/service_inspectors/dns/CMakeFiles/dns.dir/build
.PHONY : dns/fast

#=============================================================================
# Target rules for targets named ftp_telnet

# Build rule for target.
ftp_telnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ftp_telnet
.PHONY : ftp_telnet

# fast build rule for target.
ftp_telnet/fast:
	$(MAKE) -f src/service_inspectors/ftp_telnet/CMakeFiles/ftp_telnet.dir/build.make src/service_inspectors/ftp_telnet/CMakeFiles/ftp_telnet.dir/build
.PHONY : ftp_telnet/fast

#=============================================================================
# Target rules for targets named gtp_inspect

# Build rule for target.
gtp_inspect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtp_inspect
.PHONY : gtp_inspect

# fast build rule for target.
gtp_inspect/fast:
	$(MAKE) -f src/service_inspectors/gtp/CMakeFiles/gtp_inspect.dir/build.make src/service_inspectors/gtp/CMakeFiles/gtp_inspect.dir/build
.PHONY : gtp_inspect/fast

#=============================================================================
# Target rules for targets named imap

# Build rule for target.
imap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 imap
.PHONY : imap

# fast build rule for target.
imap/fast:
	$(MAKE) -f src/service_inspectors/imap/CMakeFiles/imap.dir/build.make src/service_inspectors/imap/CMakeFiles/imap.dir/build
.PHONY : imap/fast

#=============================================================================
# Target rules for targets named modbus

# Build rule for target.
modbus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 modbus
.PHONY : modbus

# fast build rule for target.
modbus/fast:
	$(MAKE) -f src/service_inspectors/modbus/CMakeFiles/modbus.dir/build.make src/service_inspectors/modbus/CMakeFiles/modbus.dir/build
.PHONY : modbus/fast

#=============================================================================
# Target rules for targets named http_inspect

# Build rule for target.
http_inspect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_inspect
.PHONY : http_inspect

# fast build rule for target.
http_inspect/fast:
	$(MAKE) -f src/service_inspectors/http_inspect/CMakeFiles/http_inspect.dir/build.make src/service_inspectors/http_inspect/CMakeFiles/http_inspect.dir/build
.PHONY : http_inspect/fast

#=============================================================================
# Target rules for targets named http2_inspect

# Build rule for target.
http2_inspect: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http2_inspect
.PHONY : http2_inspect

# fast build rule for target.
http2_inspect/fast:
	$(MAKE) -f src/service_inspectors/http2_inspect/CMakeFiles/http2_inspect.dir/build.make src/service_inspectors/http2_inspect/CMakeFiles/http2_inspect.dir/build
.PHONY : http2_inspect/fast

#=============================================================================
# Target rules for targets named pop

# Build rule for target.
pop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pop
.PHONY : pop

# fast build rule for target.
pop/fast:
	$(MAKE) -f src/service_inspectors/pop/CMakeFiles/pop.dir/build.make src/service_inspectors/pop/CMakeFiles/pop.dir/build
.PHONY : pop/fast

#=============================================================================
# Target rules for targets named rpc_decode

# Build rule for target.
rpc_decode: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rpc_decode
.PHONY : rpc_decode

# fast build rule for target.
rpc_decode/fast:
	$(MAKE) -f src/service_inspectors/rpc_decode/CMakeFiles/rpc_decode.dir/build.make src/service_inspectors/rpc_decode/CMakeFiles/rpc_decode.dir/build
.PHONY : rpc_decode/fast

#=============================================================================
# Target rules for targets named sip

# Build rule for target.
sip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sip
.PHONY : sip

# fast build rule for target.
sip/fast:
	$(MAKE) -f src/service_inspectors/sip/CMakeFiles/sip.dir/build.make src/service_inspectors/sip/CMakeFiles/sip.dir/build
.PHONY : sip/fast

#=============================================================================
# Target rules for targets named smtp

# Build rule for target.
smtp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 smtp
.PHONY : smtp

# fast build rule for target.
smtp/fast:
	$(MAKE) -f src/service_inspectors/smtp/CMakeFiles/smtp.dir/build.make src/service_inspectors/smtp/CMakeFiles/smtp.dir/build
.PHONY : smtp/fast

#=============================================================================
# Target rules for targets named ssh

# Build rule for target.
ssh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ssh
.PHONY : ssh

# fast build rule for target.
ssh/fast:
	$(MAKE) -f src/service_inspectors/ssh/CMakeFiles/ssh.dir/build.make src/service_inspectors/ssh/CMakeFiles/ssh.dir/build
.PHONY : ssh/fast

#=============================================================================
# Target rules for targets named ssl

# Build rule for target.
ssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ssl
.PHONY : ssl

# fast build rule for target.
ssl/fast:
	$(MAKE) -f src/service_inspectors/ssl/CMakeFiles/ssl.dir/build.make src/service_inspectors/ssl/CMakeFiles/ssl.dir/build
.PHONY : ssl/fast

#=============================================================================
# Target rules for targets named wizard

# Build rule for target.
wizard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wizard
.PHONY : wizard

# fast build rule for target.
wizard/fast:
	$(MAKE) -f src/service_inspectors/wizard/CMakeFiles/wizard.dir/build.make src/service_inspectors/wizard/CMakeFiles/wizard.dir/build
.PHONY : wizard/fast

#=============================================================================
# Target rules for targets named stream_paf

# Build rule for target.
stream_paf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_paf
.PHONY : stream_paf

# fast build rule for target.
stream_paf/fast:
	$(MAKE) -f src/stream/CMakeFiles/stream_paf.dir/build.make src/stream/CMakeFiles/stream_paf.dir/build
.PHONY : stream_paf/fast

#=============================================================================
# Target rules for targets named stream

# Build rule for target.
stream: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream
.PHONY : stream

# fast build rule for target.
stream/fast:
	$(MAKE) -f src/stream/CMakeFiles/stream.dir/build.make src/stream/CMakeFiles/stream.dir/build
.PHONY : stream/fast

#=============================================================================
# Target rules for targets named stream_base

# Build rule for target.
stream_base: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_base
.PHONY : stream_base

# fast build rule for target.
stream_base/fast:
	$(MAKE) -f src/stream/base/CMakeFiles/stream_base.dir/build.make src/stream/base/CMakeFiles/stream_base.dir/build
.PHONY : stream_base/fast

#=============================================================================
# Target rules for targets named stream_ip

# Build rule for target.
stream_ip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_ip
.PHONY : stream_ip

# fast build rule for target.
stream_ip/fast:
	$(MAKE) -f src/stream/ip/CMakeFiles/stream_ip.dir/build.make src/stream/ip/CMakeFiles/stream_ip.dir/build
.PHONY : stream_ip/fast

#=============================================================================
# Target rules for targets named stream_icmp

# Build rule for target.
stream_icmp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_icmp
.PHONY : stream_icmp

# fast build rule for target.
stream_icmp/fast:
	$(MAKE) -f src/stream/icmp/CMakeFiles/stream_icmp.dir/build.make src/stream/icmp/CMakeFiles/stream_icmp.dir/build
.PHONY : stream_icmp/fast

#=============================================================================
# Target rules for targets named stream_libtcp

# Build rule for target.
stream_libtcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_libtcp
.PHONY : stream_libtcp

# fast build rule for target.
stream_libtcp/fast:
	$(MAKE) -f src/stream/libtcp/CMakeFiles/stream_libtcp.dir/build.make src/stream/libtcp/CMakeFiles/stream_libtcp.dir/build
.PHONY : stream_libtcp/fast

#=============================================================================
# Target rules for targets named stream_tcp

# Build rule for target.
stream_tcp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_tcp
.PHONY : stream_tcp

# fast build rule for target.
stream_tcp/fast:
	$(MAKE) -f src/stream/tcp/CMakeFiles/stream_tcp.dir/build.make src/stream/tcp/CMakeFiles/stream_tcp.dir/build
.PHONY : stream_tcp/fast

#=============================================================================
# Target rules for targets named stream_udp

# Build rule for target.
stream_udp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_udp
.PHONY : stream_udp

# fast build rule for target.
stream_udp/fast:
	$(MAKE) -f src/stream/udp/CMakeFiles/stream_udp.dir/build.make src/stream/udp/CMakeFiles/stream_udp.dir/build
.PHONY : stream_udp/fast

#=============================================================================
# Target rules for targets named stream_user

# Build rule for target.
stream_user: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_user
.PHONY : stream_user

# fast build rule for target.
stream_user/fast:
	$(MAKE) -f src/stream/user/CMakeFiles/stream_user.dir/build.make src/stream/user/CMakeFiles/stream_user.dir/build
.PHONY : stream_user/fast

#=============================================================================
# Target rules for targets named stream_file

# Build rule for target.
stream_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stream_file
.PHONY : stream_file

# fast build rule for target.
stream_file/fast:
	$(MAKE) -f src/stream/file/CMakeFiles/stream_file.dir/build.make src/stream/file/CMakeFiles/stream_file.dir/build
.PHONY : stream_file/fast

#=============================================================================
# Target rules for targets named target_based

# Build rule for target.
target_based: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 target_based
.PHONY : target_based

# fast build rule for target.
target_based/fast:
	$(MAKE) -f src/target_based/CMakeFiles/target_based.dir/build.make src/target_based/CMakeFiles/target_based.dir/build
.PHONY : target_based/fast

#=============================================================================
# Target rules for targets named host_tracker

# Build rule for target.
host_tracker: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 host_tracker
.PHONY : host_tracker

# fast build rule for target.
host_tracker/fast:
	$(MAKE) -f src/host_tracker/CMakeFiles/host_tracker.dir/build.make src/host_tracker/CMakeFiles/host_tracker.dir/build
.PHONY : host_tracker/fast

#=============================================================================
# Target rules for targets named pub_sub

# Build rule for target.
pub_sub: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pub_sub
.PHONY : pub_sub

# fast build rule for target.
pub_sub/fast:
	$(MAKE) -f src/pub_sub/CMakeFiles/pub_sub.dir/build.make src/pub_sub/CMakeFiles/pub_sub.dir/build
.PHONY : pub_sub/fast

#=============================================================================
# Target rules for targets named time

# Build rule for target.
time: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 time
.PHONY : time

# fast build rule for target.
time/fast:
	$(MAKE) -f src/time/CMakeFiles/time.dir/build.make src/time/CMakeFiles/time.dir/build
.PHONY : time/fast

#=============================================================================
# Target rules for targets named profiler

# Build rule for target.
profiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 profiler
.PHONY : profiler

# fast build rule for target.
profiler/fast:
	$(MAKE) -f src/profiler/CMakeFiles/profiler.dir/build.make src/profiler/CMakeFiles/profiler.dir/build
.PHONY : profiler/fast

#=============================================================================
# Target rules for targets named utils

# Build rule for target.
utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 utils
.PHONY : utils

# fast build rule for target.
utils/fast:
	$(MAKE) -f src/utils/CMakeFiles/utils.dir/build.make src/utils/CMakeFiles/utils.dir/build
.PHONY : utils/fast

#=============================================================================
# Target rules for targets named helpers

# Build rule for target.
helpers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helpers
.PHONY : helpers

# fast build rule for target.
helpers/fast:
	$(MAKE) -f src/helpers/CMakeFiles/helpers.dir/build.make src/helpers/CMakeFiles/helpers.dir/build
.PHONY : helpers/fast

#=============================================================================
# Target rules for targets named lua

# Build rule for target.
lua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lua
.PHONY : lua

# fast build rule for target.
lua/fast:
	$(MAKE) -f src/lua/CMakeFiles/lua.dir/build.make src/lua/CMakeFiles/lua.dir/build
.PHONY : lua/fast

#=============================================================================
# Target rules for targets named decompress

# Build rule for target.
decompress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 decompress
.PHONY : decompress

# fast build rule for target.
decompress/fast:
	$(MAKE) -f src/decompress/CMakeFiles/decompress.dir/build.make src/decompress/CMakeFiles/decompress.dir/build
.PHONY : decompress/fast

#=============================================================================
# Target rules for targets named ips_options

# Build rule for target.
ips_options: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ips_options
.PHONY : ips_options

# fast build rule for target.
ips_options/fast:
	$(MAKE) -f src/ips_options/CMakeFiles/ips_options.dir/build.make src/ips_options/CMakeFiles/ips_options.dir/build
.PHONY : ips_options/fast

#=============================================================================
# Target rules for targets named loggers

# Build rule for target.
loggers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 loggers
.PHONY : loggers

# fast build rule for target.
loggers/fast:
	$(MAKE) -f src/loggers/CMakeFiles/loggers.dir/build.make src/loggers/CMakeFiles/loggers.dir/build
.PHONY : loggers/fast

#=============================================================================
# Target rules for targets named network_inspectors

# Build rule for target.
network_inspectors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 network_inspectors
.PHONY : network_inspectors

# fast build rule for target.
network_inspectors/fast:
	$(MAKE) -f src/network_inspectors/CMakeFiles/network_inspectors.dir/build.make src/network_inspectors/CMakeFiles/network_inspectors.dir/build
.PHONY : network_inspectors/fast

#=============================================================================
# Target rules for targets named appid

# Build rule for target.
appid: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 appid
.PHONY : appid

# fast build rule for target.
appid/fast:
	$(MAKE) -f src/network_inspectors/appid/CMakeFiles/appid.dir/build.make src/network_inspectors/appid/CMakeFiles/appid.dir/build
.PHONY : appid/fast

#=============================================================================
# Target rules for targets named arp_spoof

# Build rule for target.
arp_spoof: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 arp_spoof
.PHONY : arp_spoof

# fast build rule for target.
arp_spoof/fast:
	$(MAKE) -f src/network_inspectors/arp_spoof/CMakeFiles/arp_spoof.dir/build.make src/network_inspectors/arp_spoof/CMakeFiles/arp_spoof.dir/build
.PHONY : arp_spoof/fast

#=============================================================================
# Target rules for targets named binder

# Build rule for target.
binder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binder
.PHONY : binder

# fast build rule for target.
binder/fast:
	$(MAKE) -f src/network_inspectors/binder/CMakeFiles/binder.dir/build.make src/network_inspectors/binder/CMakeFiles/binder.dir/build
.PHONY : binder/fast

#=============================================================================
# Target rules for targets named normalize

# Build rule for target.
normalize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 normalize
.PHONY : normalize

# fast build rule for target.
normalize/fast:
	$(MAKE) -f src/network_inspectors/normalize/CMakeFiles/normalize.dir/build.make src/network_inspectors/normalize/CMakeFiles/normalize.dir/build
.PHONY : normalize/fast

#=============================================================================
# Target rules for targets named packet_capture

# Build rule for target.
packet_capture: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 packet_capture
.PHONY : packet_capture

# fast build rule for target.
packet_capture/fast:
	$(MAKE) -f src/network_inspectors/packet_capture/CMakeFiles/packet_capture.dir/build.make src/network_inspectors/packet_capture/CMakeFiles/packet_capture.dir/build
.PHONY : packet_capture/fast

#=============================================================================
# Target rules for targets named packet_tracer

# Build rule for target.
packet_tracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 packet_tracer
.PHONY : packet_tracer

# fast build rule for target.
packet_tracer/fast:
	$(MAKE) -f src/network_inspectors/packet_tracer/CMakeFiles/packet_tracer.dir/build.make src/network_inspectors/packet_tracer/CMakeFiles/packet_tracer.dir/build
.PHONY : packet_tracer/fast

#=============================================================================
# Target rules for targets named perf_monitor

# Build rule for target.
perf_monitor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 perf_monitor
.PHONY : perf_monitor

# fast build rule for target.
perf_monitor/fast:
	$(MAKE) -f src/network_inspectors/perf_monitor/CMakeFiles/perf_monitor.dir/build.make src/network_inspectors/perf_monitor/CMakeFiles/perf_monitor.dir/build
.PHONY : perf_monitor/fast

#=============================================================================
# Target rules for targets named port_scan

# Build rule for target.
port_scan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 port_scan
.PHONY : port_scan

# fast build rule for target.
port_scan/fast:
	$(MAKE) -f src/network_inspectors/port_scan/CMakeFiles/port_scan.dir/build.make src/network_inspectors/port_scan/CMakeFiles/port_scan.dir/build
.PHONY : port_scan/fast

#=============================================================================
# Target rules for targets named reputation

# Build rule for target.
reputation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reputation
.PHONY : reputation

# fast build rule for target.
reputation/fast:
	$(MAKE) -f src/network_inspectors/reputation/CMakeFiles/reputation.dir/build.make src/network_inspectors/reputation/CMakeFiles/reputation.dir/build
.PHONY : reputation/fast

#=============================================================================
# Target rules for targets named search_engines

# Build rule for target.
search_engines: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 search_engines
.PHONY : search_engines

# fast build rule for target.
search_engines/fast:
	$(MAKE) -f src/search_engines/CMakeFiles/search_engines.dir/build.make src/search_engines/CMakeFiles/search_engines.dir/build
.PHONY : search_engines/fast

#=============================================================================
# Target rules for targets named side_channel

# Build rule for target.
side_channel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 side_channel
.PHONY : side_channel

# fast build rule for target.
side_channel/fast:
	$(MAKE) -f src/side_channel/CMakeFiles/side_channel.dir/build.make src/side_channel/CMakeFiles/side_channel.dir/build
.PHONY : side_channel/fast

#=============================================================================
# Target rules for targets named connectors

# Build rule for target.
connectors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 connectors
.PHONY : connectors

# fast build rule for target.
connectors/fast:
	$(MAKE) -f src/connectors/CMakeFiles/connectors.dir/build.make src/connectors/CMakeFiles/connectors.dir/build
.PHONY : connectors/fast

#=============================================================================
# Target rules for targets named file_connector

# Build rule for target.
file_connector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file_connector
.PHONY : file_connector

# fast build rule for target.
file_connector/fast:
	$(MAKE) -f src/connectors/file_connector/CMakeFiles/file_connector.dir/build.make src/connectors/file_connector/CMakeFiles/file_connector.dir/build
.PHONY : file_connector/fast

#=============================================================================
# Target rules for targets named tcp_connector

# Build rule for target.
tcp_connector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tcp_connector
.PHONY : tcp_connector

# fast build rule for target.
tcp_connector/fast:
	$(MAKE) -f src/connectors/tcp_connector/CMakeFiles/tcp_connector.dir/build.make src/connectors/tcp_connector/CMakeFiles/tcp_connector.dir/build
.PHONY : tcp_connector/fast

#=============================================================================
# Target rules for targets named u2boat

# Build rule for target.
u2boat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u2boat
.PHONY : u2boat

# fast build rule for target.
u2boat/fast:
	$(MAKE) -f tools/u2boat/CMakeFiles/u2boat.dir/build.make tools/u2boat/CMakeFiles/u2boat.dir/build
.PHONY : u2boat/fast

#=============================================================================
# Target rules for targets named u2spewfoo

# Build rule for target.
u2spewfoo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 u2spewfoo
.PHONY : u2spewfoo

# fast build rule for target.
u2spewfoo/fast:
	$(MAKE) -f tools/u2spewfoo/CMakeFiles/u2spewfoo.dir/build.make tools/u2spewfoo/CMakeFiles/u2spewfoo.dir/build
.PHONY : u2spewfoo/fast

#=============================================================================
# Target rules for targets named snort2lua

# Build rule for target.
snort2lua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snort2lua
.PHONY : snort2lua

# fast build rule for target.
snort2lua/fast:
	$(MAKE) -f tools/snort2lua/CMakeFiles/snort2lua.dir/build.make tools/snort2lua/CMakeFiles/snort2lua.dir/build
.PHONY : snort2lua/fast

#=============================================================================
# Target rules for targets named config_states

# Build rule for target.
config_states: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config_states
.PHONY : config_states

# fast build rule for target.
config_states/fast:
	$(MAKE) -f tools/snort2lua/config_states/CMakeFiles/config_states.dir/build.make tools/snort2lua/config_states/CMakeFiles/config_states.dir/build
.PHONY : config_states/fast

#=============================================================================
# Target rules for targets named conversion_data

# Build rule for target.
conversion_data: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 conversion_data
.PHONY : conversion_data

# fast build rule for target.
conversion_data/fast:
	$(MAKE) -f tools/snort2lua/data/CMakeFiles/conversion_data.dir/build.make tools/snort2lua/data/CMakeFiles/conversion_data.dir/build
.PHONY : conversion_data/fast

#=============================================================================
# Target rules for targets named data_types

# Build rule for target.
data_types: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 data_types
.PHONY : data_types

# fast build rule for target.
data_types/fast:
	$(MAKE) -f tools/snort2lua/data/data_types/CMakeFiles/data_types.dir/build.make tools/snort2lua/data/data_types/CMakeFiles/data_types.dir/build
.PHONY : data_types/fast

#=============================================================================
# Target rules for targets named snort2lua_helpers

# Build rule for target.
snort2lua_helpers: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snort2lua_helpers
.PHONY : snort2lua_helpers

# fast build rule for target.
snort2lua_helpers/fast:
	$(MAKE) -f tools/snort2lua/helpers/CMakeFiles/snort2lua_helpers.dir/build.make tools/snort2lua/helpers/CMakeFiles/snort2lua_helpers.dir/build
.PHONY : snort2lua_helpers/fast

#=============================================================================
# Target rules for targets named keyword_states

# Build rule for target.
keyword_states: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 keyword_states
.PHONY : keyword_states

# fast build rule for target.
keyword_states/fast:
	$(MAKE) -f tools/snort2lua/keyword_states/CMakeFiles/keyword_states.dir/build.make tools/snort2lua/keyword_states/CMakeFiles/keyword_states.dir/build
.PHONY : keyword_states/fast

#=============================================================================
# Target rules for targets named output_states

# Build rule for target.
output_states: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 output_states
.PHONY : output_states

# fast build rule for target.
output_states/fast:
	$(MAKE) -f tools/snort2lua/output_states/CMakeFiles/output_states.dir/build.make tools/snort2lua/output_states/CMakeFiles/output_states.dir/build
.PHONY : output_states/fast

#=============================================================================
# Target rules for targets named preprocessor_states

# Build rule for target.
preprocessor_states: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 preprocessor_states
.PHONY : preprocessor_states

# fast build rule for target.
preprocessor_states/fast:
	$(MAKE) -f tools/snort2lua/preprocessor_states/CMakeFiles/preprocessor_states.dir/build.make tools/snort2lua/preprocessor_states/CMakeFiles/preprocessor_states.dir/build
.PHONY : preprocessor_states/fast

#=============================================================================
# Target rules for targets named rule_states

# Build rule for target.
rule_states: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rule_states
.PHONY : rule_states

# fast build rule for target.
rule_states/fast:
	$(MAKE) -f tools/snort2lua/rule_states/CMakeFiles/rule_states.dir/build.make tools/snort2lua/rule_states/CMakeFiles/rule_states.dir/build
.PHONY : rule_states/fast

#=============================================================================
# Target rules for targets named all_built_sources

# Build rule for target.
all_built_sources: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_built_sources
.PHONY : all_built_sources

# fast build rule for target.
all_built_sources/fast:
	$(MAKE) -f doc/CMakeFiles/all_built_sources.dir/build.make doc/CMakeFiles/all_built_sources.dir/build
.PHONY : all_built_sources/fast

#=============================================================================
# Target rules for targets named snort_manuals

# Build rule for target.
snort_manuals: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snort_manuals
.PHONY : snort_manuals

# fast build rule for target.
snort_manuals/fast:
	$(MAKE) -f doc/CMakeFiles/snort_manuals.dir/build.make doc/CMakeFiles/snort_manuals.dir/build
.PHONY : snort_manuals/fast

#=============================================================================
# Target rules for targets named daq_hext

# Build rule for target.
daq_hext: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daq_hext
.PHONY : daq_hext

# fast build rule for target.
daq_hext/fast:
	$(MAKE) -f daqs/CMakeFiles/daq_hext.dir/build.make daqs/CMakeFiles/daq_hext.dir/build
.PHONY : daq_hext/fast

#=============================================================================
# Target rules for targets named daq_file

# Build rule for target.
daq_file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 daq_file
.PHONY : daq_file

# fast build rule for target.
daq_file/fast:
	$(MAKE) -f daqs/CMakeFiles/daq_file.dir/build.make daqs/CMakeFiles/daq_file.dir/build
.PHONY : daq_file/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... package"
	@echo "... package_source"
	@echo "... uninstall"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... snort"
	@echo "... ips_actions"
	@echo "... codecs"
	@echo "... root_codecs"
	@echo "... link_codecs"
	@echo "... ip_codecs"
	@echo "... misc_codecs"
	@echo "... control"
	@echo "... detection"
	@echo "... events"
	@echo "... file_api"
	@echo "... filter"
	@echo "... flow"
	@echo "... framework"
	@echo "... api_options"
	@echo "... hash"
	@echo "... latency"
	@echo "... log"
	@echo "... main"
	@echo "... managers"
	@echo "... memory"
	@echo "... mime"
	@echo "... packet_io"
	@echo "... parser"
	@echo "... ports"
	@echo "... protocols"
	@echo "... sfip"
	@echo "... sfrt"
	@echo "... service_inspectors"
	@echo "... back_orifice"
	@echo "... dce_rpc"
	@echo "... dnp3"
	@echo "... dns"
	@echo "... ftp_telnet"
	@echo "... gtp_inspect"
	@echo "... imap"
	@echo "... modbus"
	@echo "... http_inspect"
	@echo "... http2_inspect"
	@echo "... pop"
	@echo "... rpc_decode"
	@echo "... sip"
	@echo "... smtp"
	@echo "... ssh"
	@echo "... ssl"
	@echo "... wizard"
	@echo "... stream_paf"
	@echo "... stream"
	@echo "... stream_base"
	@echo "... stream_ip"
	@echo "... stream_icmp"
	@echo "... stream_libtcp"
	@echo "... stream_tcp"
	@echo "... stream_udp"
	@echo "... stream_user"
	@echo "... stream_file"
	@echo "... target_based"
	@echo "... host_tracker"
	@echo "... pub_sub"
	@echo "... time"
	@echo "... profiler"
	@echo "... utils"
	@echo "... helpers"
	@echo "... lua"
	@echo "... decompress"
	@echo "... ips_options"
	@echo "... loggers"
	@echo "... network_inspectors"
	@echo "... appid"
	@echo "... arp_spoof"
	@echo "... binder"
	@echo "... normalize"
	@echo "... packet_capture"
	@echo "... packet_tracer"
	@echo "... perf_monitor"
	@echo "... port_scan"
	@echo "... reputation"
	@echo "... search_engines"
	@echo "... side_channel"
	@echo "... connectors"
	@echo "... file_connector"
	@echo "... tcp_connector"
	@echo "... u2boat"
	@echo "... u2spewfoo"
	@echo "... snort2lua"
	@echo "... config_states"
	@echo "... conversion_data"
	@echo "... data_types"
	@echo "... snort2lua_helpers"
	@echo "... keyword_states"
	@echo "... output_states"
	@echo "... preprocessor_states"
	@echo "... rule_states"
	@echo "... all_built_sources"
	@echo "... snort_manuals"
	@echo "... daq_hext"
	@echo "... daq_file"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

