.Dd January 3, 1999
.Dt SNORT-STAT 8
.Os Gnu/Linux
.Sh NAME
.Nm snort-stat
.Nd generates statistic of scans detected by snort
.Sh SYNOPSIS
.Nm cat /var/log/auth.log | /usr/sbin/snort-stat 
.Sh DESCRIPTION
.Nm snort-stat
is a small script that generates a nice statistic on the port scans that
were detected by snort and reported via /var/log/snort/alert .
The output of this script is mailed to the user confgured in  the
/etc/snort/snort.debian.conf
configuration file.
The cron script /etc/cron.daily/5snort uses this script.
.Sh SEE ALSO
.Xr snort 8
.Sh AUTHORS
The script is mostly based on the snort-stat from Yen-Ming Chen <chenym+@CMU.EDU>.
The hostname resolving, the big shrinkage and this manpage were done by 
Christian Hammers <ch@debian.org>.
