find_package(PkgConfig)
pkg_check_modules(PC_RDKAFKA rdkafka)

if (PC_RDKAFKA_FOUND)
  set(RDKAFKA_LIBRARIES ${PC_RDKAFKA_LIBRARIES})
  set(RDKAFKA_INCLUDE_DIRS ${PC_RDKAFKA_INCLUDE_DIRS})
endif()

find_path(RDKAFKA_INCLUDE_DIR
  NAMES rdkafka.h
  HINTS ${RDKAFKA_INCLUDE_DIR_HINT} ${PC_RDKAFKA_INCLUDEDIR}
)

find_library(RDKAFKA_LIBRARY
  NAMES rdkafka
  HINTS ${RDKAFKA_LIBRARIES_DIR_HINT} ${PC_RDKAFKA_LIBDIR}
)

if (RDKAFKA_INCLUDE_DIR AND RDKAFKA_LIBRARY)
  set(HAVE_RDKAFKA TRUE)
endif()

if (NOT ENABLE_ALERT_KAFKA)
  set(HAVE_RDKAFKA FALSE)
endif()

mark_as_advanced(
  RDKAFKA_INCLUDE_DIR
  RDKAFKA_LIBRARY
)