
# required libraries
find_package(Threads REQUIRED)
find_package(DAQ REQUIRED)
find_package(DNET REQUIRED)
find_package(FlexLexer REQUIRED)
find_package(HWLOC REQUIRED)
find_package(LuaJIT REQUIRED)
find_package(OpenSSL 1.1.1 REQUIRED)
find_package(PCAP REQUIRED)
find_package(PCRE REQUIRED)
find_package(ZLIB REQUIRED)
if (ENABLE_UNIT_TESTS)
    find_package(CppUTest REQUIRED)
endif (ENABLE_UNIT_TESTS)

# optional libraries
find_package(Atomic QUIET)
find_package(LibLZMA QUIET)
find_package(Asciidoc QUIET)
find_package(DBLATEX QUIET)
find_package(Ruby QUIET 1.8.7)
find_package(HS QUIET 4.4.0)
if (ENABLE_SAFEC)
    find_package(SafeC QUIET)
endif (ENABLE_SAFEC)
find_package(ICONV QUIET)
find_package(UUID QUIET)
find_package(Libunwind)
find_package(NUMA QUIET)
find_package(ML QUIET)
