


##  FOO FOR BUILDING ARCHIVE PACKAGES!!

set (CPACK_GENERATOR TGZ ZIP TGZ TZ STGZ)
set (CPACK_PACKAGE_NAME "snort")

# This will always be false unless manually set
if (BUILD_DEBIAN_ARCHIVE)
    list(APPEND CPACK_GENERATOR DEB)
endif()

SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "SNORT-TEAM") #required

# RPM foo
set( CPACK_RPM_PACKAGE_SUMMARY   "The snort RPM package summary")
set( CPACK_RPM_PACKAGE_NAME      "snort-rpm")
set( CPACK_RPM_PACKAGE_VERSION   "${SNORT_VERSION_MAJOR}.${SNORT_VERSION_MINOR}.${SNORT_VERSION_BUILD}")
set( CPACK_RPM_PACKAGE_ARCHITECTURE      "noarch")
set (CPACK_RPM_PACKAGE_RELEASE   1)
set( CPACK_RPM_PACKAGE_LICENSE   "unknown")
#set( CPACK_RPM_PACKAGE_GROUP   "unknown")
set( CPACK_RPM_PACKAGE_VENDOR   "Cisco")
set( CPACK_RPM_PACKAGE_DESCRIPTION "Snort RPM")


include(CPack)

